services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: hamon
      POSTGRES_PASSWORD: hamon_secret
      POSTGRES_DB: hamon
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
